### ISSUE TITLE
Wstępny wygląd interfejsu

### ISSUE THREAD

**Issue by Pa16gr** [Pa16gr/Your_Workout#1]

**Comment by Pa16gr** [comment]
![20200320_194814](https://user-images.githubusercontent.com/38064543/77196820-62bf1880-6ae4-11ea-839e-9b91c5077fcd.jpg)

**Comment by Pa16gr** [comment]
![20200320_194814](https://user-images.githubusercontent.com/38064543/77196872-75d1e880-6ae4-11ea-92fa-547c9d6d7023.jpg)

**Comment by xMelaa** [comment]
![pierwszewejscie](https://user-images.githubusercontent.com/62288662/79903276-146aa580-8413-11ea-8d2e-a1964fbb8fbe.png)
