### ISSUE TITLE
Skategoryzowanie ćwiczeń

### ISSUE THREAD

**Issue by Pa16gr** [Pa16gr/Your_Workout#3]

**Comment by xMelaa** [comment]
![Scan](https://user-images.githubusercontent.com/62288662/77202939-9489ac80-6aef-11ea-8387-f0695b45a11c.jpg)

**Comment by Pa16gr** [comment]
Movement:
- Pull Horizontal
- Pull Vertical
- Push Horizontal
- Push Vertical
- Hip Dominant
- Knee Dominant
- ABS
- Core
- Anti-rotation
- Anti-flexion

Name

Category:
- Power
- Strength
- Accessory

Type:
-Unilateral (jedno)
-Bilateral (obu)

isPrime:
-True
-False

**Comment by Pa16gr** [comment]
**Pull Horizontal:**
- Bent Over Row
- Inverted Row
- Single Arm Band Row
- Face Pull
**Pull Vertical**
- Pull Up
- Chin Up
- Barbell Curl
**Push Horizontal**
- Bench Press
- Push Ups
- Ball Throw
- Single Arm KB Bench Press
**Pull Vertical**
- Barbell Overhead Press
- KB Overhead Press
- Dips
**Hip Dominant**
- Deadlift
- Glute Bridge
- Single Leg Romanian Deadlift
**Knee Dominant**
- Back Squat
- Front Squat
- Goblet Squat
- Lunges
- Terminal Knee Extension
**ABS**
- Knee Raises
- Leg Raises
**Core**
- Plank
- High Plank
**Anti-rotation**
- Pallof Press
- Half Kneeling Pallof Press
**Anti-flexion**
- Suitcase Carry
- Farmers Walk
